FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

FROM node:20-alpine
WORKDIR /app
RUN mkdir -p uploads/photos
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 5001
CMD ["node", "server.js"]